name: house_of_deliverance
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.3.3+6  

environment:
  sdk: '>=2.19.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  get: ^4.6.5
  connectivity_plus: ^2.3.6
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  firebase_messaging: ^14.4.1
  flutter_local_notifications: ^14.0.0
  flutter_switch: ^0.3.2
  carousel_slider: ^4.0.0
  smooth_page_indicator: ^1.0.0+2
  intl: ^0.17.0
  fluttertoast: ^8.0.8
  permission_handler: ^10.0.0
  images_picker: ^1.2.11
  url_launcher: 6.0.20
  firebase_core: ^2.11.0
  firebase_auth: ^4.5.0
  cloud_firestore: ^4.6.0
  firebase_storage: ^11.1.2
  sqflite: ^2.2.8+2
  path_provider: ^2.0.14
  flutter_staggered_grid_view: ^0.6.2
  flutter_tts: ^3.6.3
  country_code_picker: ^3.0.0
  country_picker: ^2.0.20
  wakelock: ^0.6.2
  change_app_package_name: ^1.1.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Urbanist
      fonts: 
        - asset: assets/fonts/UrbanistMedium.ttf
          weight: 500
        - asset: assets/fonts/UrbanistBold.ttf
          weight: 700
        - asset: assets/fonts/UrbanistRegular.ttf
          weight: 400
        - asset: assets/fonts/UrbanistSemiBold.ttf
          weight: 600