// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAve7cR7a1HJnUP3jyJg1-fd8azXNZLBiE',
    appId: '1:970617513621:web:e759beb19799718007dd9c',
    messagingSenderId: '970617513621',
    projectId: 'hodnagpur',
    authDomain: 'hodnagpur.firebaseapp.com',
    storageBucket: 'hodnagpur.appspot.com',
    measurementId: 'G-KZ69SRW2ER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAWr00u3tP8ljtRtFkCbdQT94WiubFu_4',
    appId: '1:970617513621:android:36d6582d1cd78d3107dd9c',
    messagingSenderId: '970617513621',
    projectId: 'hodnagpur',
    storageBucket: 'hodnagpur.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfqnCwcDhKgj5L6C-jDoL5hj636t3c3ks',
    appId: '1:970617513621:ios:e63046ced9c09b6907dd9c',
    messagingSenderId: '970617513621',
    projectId: 'hodnagpur',
    storageBucket: 'hodnagpur.appspot.com',
    iosClientId: '970617513621-i1klc68h3qj7kkmfo1oqk3k2debvqj3c.apps.googleusercontent.com',
    iosBundleId: 'com.christianappdevelopers.hod2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfqnCwcDhKgj5L6C-jDoL5hj636t3c3ks',
    appId: '1:970617513621:ios:539048644e8d0ad107dd9c',
    messagingSenderId: '970617513621',
    projectId: 'hodnagpur',
    storageBucket: 'hodnagpur.appspot.com',
    iosClientId: '970617513621-00sprgmar8ac9hnmbkjv4oq6pc30rh21.apps.googleusercontent.com',
    iosBundleId: 'com.christianappdevelopers.hod2.RunnerTests',
  );
}
